# User Features
In this notebook I will create the columns of interesting features per user, that will help me create the groups.

In [1]:
import pandas as pd

# sessions trip rate

In [2]:
sessions = pd.read_csv('data/preprocessed_data/sessions_preprocessed.csv')

In [11]:
sessions["user_id"]

0        676570
1        676707
2        682247
3        684521
4        684764
          ...
48678    646455
48679    656708
48680    659161
48681    662750
48682    668172
Name: user_id, Length: 48683, dtype: int64

In [41]:
sessions_dummy =  sessions[sessions["user_id"] == 676570].copy()

In [42]:
sessions_dummy.sort_values("session_start", inplace=True)

In [43]:
sessions_dummy

,session_id,user_id,trip_id,session_start,session_end,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
22900,676570-bc34363f976245daa5a37637a5b6b571,676570,NaN,2023-03-19 10:36:00,2023-03-19 10:36:23,NaN,NaN,False,False,3,False
23539,676570-476c004a99b649cc817dd5168d4fa1e7,676570,NaN,2023-03-23 21:14:00,2023-03-23 21:15:17,NaN,NaN,False,False,10,False
0,676570-f883c6e630f641cd9ca5ac61ae7045d5,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-27 19:37:00,2023-03-27 19:49:41,NaN,NaN,True,True,103,False
8608,676570-9f61d9d86a3445aba4e79c03eeca0529,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-04-02 19:49:41,2023-04-02 21:14:46.737776,NaN,NaN,True,True,85,True
1381,676570-a6b1d6632bd94a09beddb104e112b097,676570,NaN,2023-04-10 11:43:00,2023-04-10 11:46:14,NaN,NaN,False,False,26,False
2840,676570-c115bd0b346241bf9521b6937e43104e,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-29 21:07:00,2023-04-29 21:10:00,NaN,NaN,True,True,24,False
5551,676570-06b9f6c75c5a48d3b065d555a17d0cdd,676570,NaN,2023-06-06 11:54:00,2023-06-06 11:54:15,NaN,NaN,False,False,2,False
7353,676570-79c39a0b395c41c99012e7611821c4f2,676570,NaN,2023-07-03 08:51:00,2023-07-03 08:54:20,0.15,NaN,False,False,27,False

In [44]:
sessions_dummy["trip_id"] = sessions_dummy["trip_id"].bfill()

In [45]:
sessions_dummy

,session_id,user_id,trip_id,session_start,session_end,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
22900,676570-bc34363f976245daa5a37637a5b6b571,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-19 10:36:00,2023-03-19 10:36:23,NaN,NaN,False,False,3,False
23539,676570-476c004a99b649cc817dd5168d4fa1e7,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-23 21:14:00,2023-03-23 21:15:17,NaN,NaN,False,False,10,False
0,676570-f883c6e630f641cd9ca5ac61ae7045d5,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-27 19:37:00,2023-03-27 19:49:41,NaN,NaN,True,True,103,False
8608,676570-9f61d9d86a3445aba4e79c03eeca0529,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-04-02 19:49:41,2023-04-02 21:14:46.737776,NaN,NaN,True,True,85,True
1381,676570-a6b1d6632bd94a09beddb104e112b097,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-10 11:43:00,2023-04-10 11:46:14,NaN,NaN,False,False,26,False
2840,676570-c115bd0b346241bf9521b6937e43104e,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-29 21:07:00,2023-04-29 21:10:00,NaN,NaN,True,True,24,False
5551,676570-06b9f6c75c5a48d3b065d555a17d0cdd,676570,NaN,2023-06-06 11:54:00,2023-06-06 11:54:15,NaN,NaN,False,False,2,False
7353,676570-79c39a0b395c41c99012e7611821c4f2,676570,NaN,2023-07-03 08:51:00,2023-07-03 08:54:20,0.15,NaN,False,False,27,False

### working on the cancellations

In [36]:
sessions_dummy

,session_id,user_id,trip_id,session_start,session_end,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
22900,676570-bc34363f976245daa5a37637a5b6b571,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-19 10:36:00,2023-03-19 10:36:23,NaN,NaN,False,False,3,False
23539,676570-476c004a99b649cc817dd5168d4fa1e7,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-23 21:14:00,2023-03-23 21:15:17,NaN,NaN,False,False,10,False
0,676570-f883c6e630f641cd9ca5ac61ae7045d5,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-03-27 19:37:00,2023-03-27 19:49:41,NaN,NaN,True,True,103,False
8608,676570-9f61d9d86a3445aba4e79c03eeca0529,676570,676570-ed23a4a861404b84b240ca68b9da1cb3,2023-04-02 19:49:41,2023-04-02 21:14:46.737776,NaN,NaN,True,True,85,True
1381,676570-a6b1d6632bd94a09beddb104e112b097,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-10 11:43:00,2023-04-10 11:46:14,NaN,NaN,False,False,26,False
2840,676570-c115bd0b346241bf9521b6937e43104e,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-29 21:07:00,2023-04-29 21:10:00,NaN,NaN,True,True,24,False
5551,676570-06b9f6c75c5a48d3b065d555a17d0cdd,676570,NaN,2023-06-06 11:54:00,2023-06-06 11:54:15,NaN,NaN,False,False,2,False
7353,676570-79c39a0b395c41c99012e7611821c4f2,676570,NaN,2023-07-03 08:51:00,2023-07-03 08:54:20,0.15,NaN,False,False,27,False

In [37]:
invalid_id = sessions_dummy[sessions_dummy["cancellation"]]["trip_id"]

In [40]:
sessions_dummy[~sessions_dummy["trip_id"].isin(invalid_id)]

,session_id,user_id,trip_id,session_start,session_end,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
1381,676570-a6b1d6632bd94a09beddb104e112b097,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-10 11:43:00,2023-04-10 11:46:14,NaN,NaN,False,False,26,False
2840,676570-c115bd0b346241bf9521b6937e43104e,676570,676570-ced357d95e244137b12aad2ffd7fa868,2023-04-29 21:07:00,2023-04-29 21:10:00,NaN,NaN,True,True,24,False
5551,676570-06b9f6c75c5a48d3b065d555a17d0cdd,676570,NaN,2023-06-06 11:54:00,2023-06-06 11:54:15,NaN,NaN,False,False,2,False
7353,676570-79c39a0b395c41c99012e7611821c4f2,676570,NaN,2023-07-03 08:51:00,2023-07-03 08:54:20,0.15,NaN,False,False,27,False